### PR TITLE
Material entry improvements

### PR DESCRIPTION
**Pull request by ArtjomP**
Properties have been added to the MaterialEntry:
- HiddenLabelTextSize;
- PlaceholderColor;
- TextBackgroundColor;
- TextColor.

May it's good for issue #25.

### CODE REVIEW

**Comment by SuavePirate** [comment]
Love this PR. Only issue I have is with the default hidden label size. We should make the default size the current size so that there are no regression issues with people who update to the latest but don't apply the HiddenLabelSize.

**Comment by ArtjomP** [comment]
No problem, I returned it to 10 by default. I think that control is great but has no a lot of users and by default 10 looks not so cool on every device.
You bet!

**Comment by ArtjomP** [comment]
Please, don't merge it yet. It seems there is a bug. I'm investigating it

**Comment by ArtjomP** [comment]
Done!

**Comment by jbpoulsen** [comment]
Will this version be pushed to Nuget any time soon? The TextColor property could be really useful :)

**Comment by SuavePirate** [comment]
I haven't had a lot of time to work on it since the current nuproj is having issues with netstandard2.0 where it decides to include all of the netstandard2 dlls with the package rather than as a dependency. I'll have to look at other methods of building the package to switch over to more permanently but any help in that front will be greatly appreciated:)

**Comment by ArtjomP** [comment]
I published this version:
Install-Package pt.MaterialFormControls -Version 2018.2.22-pre7
It's not publicly listed

**Comment by SuavePirate** [comment]
@ArtjomP what was your nuget build process? When using the .nuproj with netstandard2 I'm still getting a bad package with all the dlls. Are you doing it manually?

**Comment by ArtjomP** [comment]
I just opened your package from nuget.org with [Nuget Package Explorer](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer) and edited it a little bit.

**Comment by Hasanajouz** [comment]
@ArtjomP thanks very much for those improvments 😍😍

**Pull request merged**
