### PR TITLE
Added Completed Event

### PR DESCRIPTION
**Pull request by welcometoall**
Occures when the user finalizes the text in material entry with the return key.

### CODE REVIEW

**Comment by SuavePirate** [comment]
Typo in the XML comment - "Occurs".

It might also help to see an example of this, but not required to merge.

As always, thanks for contributing!

**Comment by SuavePirate** [comment]
@welcometoall looks like there is a merge conflict with other PR's merged.

**Comment by boskokg** [comment]
Hello. You have a great component. 
Can you please commit this Completed event?

Thanks in advance

**Comment by SuavePirate** [comment]
There are merge conflicts, so we can't merge it. The original author needs to fix it if they want it. But I'm also pretty sure this exists not

**Comment by SuavePirate** [comment]
This has been implemented by another PR now

**Pull request closed without merging**
